server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: membreModule
          uri: http://localhost:8087/
          predicates:
            - Path=/Member/**
        - id: coachModule
          uri: http://localhost:8086/
          predicates:
            - Path=/Coach/**
        - id: abonnementsModule
          uri: http://localhost:5000/
          predicates:
            - Path=/api/Abonnements/**
        - id: equipementsModule
          uri: http://localhost:8020/
          predicates:
            - Path=/Equipement/**
        - id: reservationsModule
          uri: http://localhost:8030/
          predicates:
            - Path=/Reservations/**
        - id: evenementsModule
          uri: http://localhost:8099/
          predicates:
            - Path=/evenements/**

